image: docker.transip.us/transip/golang:latest
stages:
  - analyze
  - lint
  - test

analyze:lint:
  stage: analyze
  image: golangci/golangci-lint:v1.19
  script:
    - golangci-lint run

lint:golint:
  stage: lint
  script:
    - ci/lint.sh
  tags:
    - k8s

lint:vet:
  stage: lint
  script:
    - ci/vet.sh
  tags:
    - k8s

lint:modtidy:
  stage: lint
  script:
    - ci/tidy.sh
  tags:
    - k8s

test:go:
  stage: test
  script:
    - ci/test.sh
  tags:
    - k8s
